# Generated by Django 4.2.5 on 2023-11-12 08:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyView', '0003_student_s_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='s_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FacultyView.branch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FacultyView.section'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FacultyView.year'),
        ),
    ]
